'use strict';
const $=id=>document.getElementById(id),FT=.3048,MPH=2.2369362921,G0=9.80665;
const map=L.map('map',{preferCanvas:true}).setView([40.7357,-74.1724],17);
const layers={boundary:L.layerGroup().addTo(map),haz:L.layerGroup().addTo(map),nogo:L.layerGroup().addTo(map),route:L.layerGroup().addTo(map),elements:L.layerGroup().addTo(map),cones:L.layerGroup().addTo(map),labels:L.layerGroup().addTo(map),temp:L.layerGroup().addTo(map),ends:L.layerGroup().addTo(map)};
const street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap'}).addTo(map);
const sat=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:20,attribution:'© Esri'});
L.control.layers({Street:street,Satellite:sat}).addTo(map);L.control.scale({imperial:true,metric:true}).addTo(map);
const colors={straight:'#60a5fa',slalom:'#facc15',offset:'#c084fc',sweeper:'#34d399',hairpin:'#fb7185',manual:'#e2e8f0'};
function blank(){return{boundary:[],hazards:[],nogos:[],start:null,finish:null,route:[],cones:[],elements:[],analysis:null,performance:null,length:0,warnings:0,settings:null}}
let S=blank(),mode=null,tmp=[];
const arr=p=>Array.isArray(p)?p:[p.lat,p.lng];
function centroidLL(poly){let a=poly.reduce((q,p)=>[q[0]+p[0],q[1]+p[1]],[0,0]);return[a[0]/poly.length,a[1]/poly.length]}
function xy(p,o){p=arr(p);o=arr(o);return{x:(p[1]-o[1])*111320*Math.cos(o[0]*Math.PI/180),y:(p[0]-o[0])*111320}}
function ll(p,o){o=arr(o);return[o[0]+p.y/111320,o[1]+p.x/(111320*Math.cos(o[0]*Math.PI/180))]}
const d2=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),lerp=(a,b,t)=>({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t}),add=(a,b)=>({x:a.x+b.x,y:a.y+b.y}),mul=(a,k)=>({x:a.x*k,y:a.y*k});
function distLL(a,b){let q=xy(b,a);return Math.hypot(q.x,q.y)}
function polyArea(poly){let a=0;for(let i=0,j=poly.length-1;i<poly.length;j=i++)a+=poly[j].x*poly[i].y-poly[i].x*poly[j].y;return Math.abs(a)/2}
function pointIn(p,poly){let z=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++)if((poly[i].y>p.y)!=(poly[j].y>p.y)&&p.x<(poly[j].x-poly[i].x)*(p.y-poly[i].y)/(poly[j].y-poly[i].y)+poly[i].x)z=!z;return z}
function pointSegDist(p,a,b){let dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return d2(p,a);let t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l));return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy)}
function edgeDist(p,poly){let m=Infinity;for(let i=0,j=poly.length-1;i<poly.length;j=i++)m=Math.min(m,pointSegDist(p,poly[j],poly[i]));return m}
function unit(a,b){let dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||1;return{u:{x:dx/l,y:dy/l},n:{x:-dy/l,y:dx/l},len:l}}
function settings(){let vehicle={street:{mu:.72,accel:.28,brake:.65,label:'Street / novice'},sport:{mu:.90,accel:.38,brake:.80,label:'Performance street'},prepared:{mu:1.10,accel:.52,brake:1.0,label:'Prepared / race tire'}}[$('vehicle').value];return{target:+$('target').value,gate:+$('gate').value*FT,edge:+$('edge').value*FT,separation:+$('separation').value*FT,slalom:Math.max(45,+$('slalom').value)*FT,seed:+$('seed').value||1,mix:$('mix').value,vehicle}}
function context(st=settings()){if(S.boundary.length<3)return null;let origin=centroidLL(S.boundary),boundary=S.boundary.map(p=>xy(p,origin)),nogos=S.nogos.map(n=>n.map(p=>xy(p,origin))),hazards=S.hazards.map(h=>({p:xy(h.p,origin),r:h.r,type:h.type})),xs=boundary.map(p=>p.x),ys=boundary.map(p=>p.y);return{origin,boundary,nogos,hazards,st,corridor:st.edge+st.gate/2,designOffset:Math.min(24*FT,Math.max(16*FT,st.gate*1.1)),bbox:{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)}}}
function safeXY(p,c,extra=0){let r=c.corridor+extra;if(!pointIn(p,c.boundary)||edgeDist(p,c.boundary)<r)return false;for(const n of c.nogos)if(pointIn(p,n)||edgeDist(p,n)<r)return false;for(const h of c.hazards)if(d2(p,h.p)<h.r+r)return false;return true}
function coneSafe(p,c){let r=c.st.edge;if(!pointIn(p,c.boundary)||edgeDist(p,c.boundary)<r)return false;for(const n of c.nogos)if(pointIn(p,n)||edgeDist(p,n)<r)return false;for(const h of c.hazards)if(d2(p,h.p)<h.r+r)return false;return true}
function lineSafe(a,b,c,extra=0,step=7*FT){let n=Math.max(2,Math.ceil(d2(a,b)/step));for(let i=0;i<=n;i++)if(!safeXY(lerp(a,b,i/n),c,extra))return false;return true}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').style.display='none',2600)}
function endpoint(p,cls,text,key){let m=L.marker(p,{draggable:true,icon:L.divIcon({className:'',html:`<div class="end ${cls}">${text}</div>`,iconSize:[27,27],iconAnchor:[13,13]})}).addTo(layers.ends);m.on('dragend',()=>{let q=m.getLatLng();S[key]=[q.lat,q.lng];S.route=[];S.elements=[];S.cones=[];S.performance=null;draw()})}
function coneIcon(c){return L.divIcon({className:'',html:`<div class="cone ${c.type||'gate'} ${c.valid?'':'bad'}"></div>`,iconSize:[12,12],iconAnchor:[6,6]})}
function draw(){Object.values(layers).forEach(g=>g.clearLayers());if(S.boundary.length)L.polygon(S.boundary,{color:'#38bdf8',weight:3,fillOpacity:.07}).addTo(layers.boundary);S.nogos.forEach((n,i)=>L.polygon(n,{color:'#ef4444',dashArray:'6 6',fillOpacity:.18}).bindTooltip('No-go '+(i+1)).addTo(layers.nogo));S.hazards.forEach(h=>{L.circle(h.p,{radius:h.r,color:'#fb7185',fillOpacity:.12}).addTo(layers.haz);L.circleMarker(h.p,{radius:6,color:'#fff',weight:2,fillColor:'#e11d48',fillOpacity:1}).bindTooltip(`${h.type}<br>${(h.r/FT).toFixed(0)} ft buffer`).addTo(layers.haz)});if(S.route.length)L.polyline(S.route,{color:'#020617',weight:9,opacity:.8}).addTo(layers.route);S.elements.forEach((e,i)=>{L.polyline(e.path,{color:colors[e.type]||'#fff',weight:5,opacity:.95}).bindTooltip(`${i+1}. ${e.name}`).addTo(layers.elements);let p=e.path[Math.floor(e.path.length/2)];L.marker(p,{interactive:false,icon:L.divIcon({className:'',html:`<div class="elabel">${i+1} ${e.short||e.type.toUpperCase()}</div>`,iconAnchor:[20,10]})}).addTo(layers.labels)});S.cones.forEach(c=>L.marker(c.p,{icon:coneIcon(c)}).bindTooltip(`Cone ${c.id} · ${c.type}<br>${c.element||''}${c.side?` · ${c.side}`:''}<br>${c.p[0].toFixed(6)}, ${c.p[1].toFixed(6)}`).addTo(layers.cones));if(S.start)endpoint(S.start,'start','S','start');if(S.finish)endpoint(S.finish,'finish','F','finish');renderLists();renderStats();renderAnalysis()}
function tempDraw(){layers.temp.clearLayers();if(tmp.length)L.polyline(tmp,{color:'#facc15',weight:3,dashArray:'5 5'}).addTo(layers.temp);tmp.forEach(p=>L.circleMarker(p,{radius:4,color:'#facc15'}).addTo(layers.temp))}
function setMode(m){mode=m;tmp=[];tempDraw();document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));let t={boundary:'Tap pavement corners, then Finish.',hazard:'Tap the hazard location.',nogo:'Tap around the exclusion, then Finish.',start:'Tap the start location.',finish:'Tap the finish location.',route:'Tap along the centerline, then Finish.'};$('modetxt').textContent=t[m]||'';$('modebar').classList.toggle('show',!!m);$('done').style.display=['boundary','nogo','route'].includes(m)?'block':'none';$('undo').style.display=$('done').style.display}
map.on('click',e=>{if(!mode)return;let p=[e.latlng.lat,e.latlng.lng];if(['boundary','nogo','route'].includes(mode)){tmp.push(p);tempDraw()}else if(mode==='hazard'){S.hazards.push({p,r:+$('hr').value*FT,type:$('ht').value});invalidateCourse();setMode(null);draw();toast('Hazard added')}else{if(S.boundary.length&&!pointIn(xy(p,centroidLL(S.boundary)),S.boundary.map(q=>xy(q,centroidLL(S.boundary)))))return toast('Place it inside the boundary');S[mode]=p;invalidateCourse();setMode(null);draw()}});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('cancel').onclick=()=>setMode(null);$('undo').onclick=()=>{tmp.pop();tempDraw()};$('done').onclick=()=>{if(mode==='boundary'&&tmp.length>2){S.boundary=[...tmp];S.start=S.finish=null;invalidateCourse();map.fitBounds(S.boundary)}else if(mode==='nogo'&&tmp.length>2){S.nogos.push([...tmp]);invalidateCourse()}else if(mode==='route'&&tmp.length>1){S.route=[...tmp];S.start=S.route[0];S.finish=S.route[S.route.length-1];manualElements()}else return toast('Add more points');setMode(null);draw()};
function invalidateCourse(){S.route=[];S.cones=[];S.elements=[];S.performance=null;S.analysis=null;S.length=0;S.warnings=0}
$('toggle').onclick=()=>{$('drawer').classList.toggle('closed');setTimeout(()=>map.invalidateSize(),260)};
$('rect').onclick=()=>{let c=map.getCenter(),w=+$('w').value*FT,h=+$('h').value*FT,a=+$('bearing').value*Math.PI/180,ca=Math.cos(a),sa=Math.sin(a);S.boundary=[[-w/2,-h/2],[w/2,-h/2],[w/2,h/2],[-w/2,h/2]].map(([x,y])=>ll({x:x*ca-y*sa,y:x*sa+y*ca},c));S.start=S.finish=null;invalidateCourse();draw();map.fitBounds(S.boundary);toast('Exact boundary placed')};
$('gps').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>map.setView([p.coords.latitude,p.coords.longitude],18),()=>toast('Location permission unavailable'),{enableHighAccuracy:true}):toast('GPS unsupported');
$('find').onclick=async()=>{let q=$('q').value.trim(),m=q.match(/^\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)\s*$/);if(m)return map.setView([+m[1],+m[2]],18);try{let a=await(await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&q='+encodeURIComponent(q))).json();$('searchres').innerHTML=a.map((x,i)=>`<div class="sr" data-i="${i}">${x.display_name}</div>`).join('')||'<div class="sr">No results</div>';$('searchres').querySelectorAll('[data-i]').forEach(e=>e.onclick=()=>{let x=a[+e.dataset.i];map.setView([+x.lat,+x.lon],18);$('searchres').innerHTML=''})}catch(e){toast('Search failed; try latitude, longitude')}};
