'use strict';
function analyzeSite(c=context()){if(!c)return null;let width=c.bbox.maxX-c.bbox.minX,height=c.bbox.maxY-c.bbox.minY,maxDim=Math.max(width,height),cell=Math.max(8*FT,Math.min(16*FT,maxDim/75)),nx=Math.ceil(width/cell),ny=Math.ceil(height/cell);if(nx*ny>12000){cell*=Math.sqrt(nx*ny/12000);nx=Math.ceil(width/cell);ny=Math.ceil(height/cell)}let usable=0,design=0,total=0;for(let iy=0;iy<ny;iy++)for(let ix=0;ix<nx;ix++){let p={x:c.bbox.minX+(ix+.5)*cell,y:c.bbox.minY+(iy+.5)*cell};if(pointIn(p,c.boundary)){total++;if(safeXY(p,c,0))usable++;if(safeXY(p,c,c.designOffset))design++}}let site=polyArea(c.boundary),usableArea=usable*cell*cell,designArea=design*cell*cell,capacity=designArea/c.st.separation*.84;return{siteArea:site,usableArea,designArea,capacity,cell,total,usable,design,availableLength:capacity,rawCapacity:capacity}}
class Heap{constructor(){this.a=[]}push(n,p){let a=this.a,i=a.length;a.push({n,p});while(i){let q=(i-1)>>1;if(a[q].p<=p)break;a[i]=a[q];i=q}a[i]={n,p}}pop(){let a=this.a;if(!a.length)return null;let root=a[0],last=a.pop();if(a.length){let i=0;while(1){let l=i*2+1,r=l+1;if(l>=a.length)break;let c=r<a.length&&a[r].p<a[l].p?r:l;if(a[c].p>=last.p)break;a[i]=a[c];i=c}a[i]=last}return root.n}get length(){return this.a.length}}
function buildGrid(c){let width=c.bbox.maxX-c.bbox.minX,height=c.bbox.maxY-c.bbox.minY,cell=Math.max(8*FT,Math.min(14*FT,c.st.separation/5));let nx=Math.ceil(width/cell)+1,ny=Math.ceil(height/cell)+1;if(nx*ny>15000){cell*=Math.sqrt(nx*ny/15000);nx=Math.ceil(width/cell)+1;ny=Math.ceil(height/cell)+1}let valid=new Uint8Array(nx*ny);for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){let p={x:c.bbox.minX+x*cell,y:c.bbox.minY+y*cell};valid[y*nx+x]=safeXY(p,c,0)?1:0}return{c,cell,nx,ny,valid,point:i=>({x:c.bbox.minX+(i%nx)*cell,y:c.bbox.minY+Math.floor(i/nx)*cell}),index:(x,y)=>y*nx+x}}
function nearestIndex(p,g){let x0=Math.round((p.x-g.c.bbox.minX)/g.cell),y0=Math.round((p.y-g.c.bbox.minY)/g.cell);for(let r=0;r<Math.max(g.nx,g.ny);r++){let best=-1,bd=Infinity;for(let y=Math.max(0,y0-r);y<=Math.min(g.ny-1,y0+r);y++)for(let x=Math.max(0,x0-r);x<=Math.min(g.nx-1,x0+r);x++)if((Math.abs(x-x0)===r||Math.abs(y-y0)===r)&&g.valid[g.index(x,y)]){let i=g.index(x,y),q=g.point(i),d=d2(p,q);if(d<bd){bd=d;best=i}}if(best>=0)return best}return-1}
function astar(a,b,g){if(lineSafe(a,b,g.c,0))return[a,b];let s=nearestIndex(a,g),goal=nearestIndex(b,g);if(s<0||goal<0)return null;let N=g.nx*g.ny,score=new Float64Array(N),came=new Int32Array(N),closed=new Uint8Array(N);score.fill(Infinity);came.fill(-1);score[s]=0;let heap=new Heap();heap.push(s,d2(g.point(s),g.point(goal)));const dirs=[[-1,-1,1.414],[-1,0,1],[-1,1,1.414],[0,-1,1],[0,1,1],[1,-1,1.414],[1,0,1],[1,1,1.414]];while(heap.length){let cur=heap.pop();if(closed[cur])continue;if(cur===goal){let ids=[];for(let q=cur;q>=0;q=came[q]){ids.push(q);if(q===s)break}ids.reverse();let path=[a,...ids.map(i=>g.point(i)),b],simple=[path[0]],i=0;while(i<path.length-1){let j=path.length-1;while(j>i+1&&!lineSafe(path[i],path[j],g.c,0))j--;simple.push(path[j]);i=j}return simple}closed[cur]=1;let x=cur%g.nx,y=Math.floor(cur/g.nx);for(const [dx,dy,w] of dirs){let xx=x+dx,yy=y+dy;if(xx<0||yy<0||xx>=g.nx||yy>=g.ny)continue;let n=g.index(xx,yy);if(!g.valid[n]||closed[n])continue;let tentative=score[cur]+w*g.cell;if(tentative<score[n]){score[n]=tentative;came[n]=cur;heap.push(n,tentative+d2(g.point(n),g.point(goal)))}}}return null}
function rotate(p,a){let c=Math.cos(a),s=Math.sin(a);return{u:p.x*c+p.y*s,v:-p.x*s+p.y*c}}
function unrotate(u,v,a){let c=Math.cos(a),s=Math.sin(a);return{x:u*c-v*s,y:u*s+v*c}}
function scanRows(c,angle,phase,pitch){let rb=c.boundary.map(p=>rotate(p,angle)),minU=Math.min(...rb.map(p=>p.u)),maxU=Math.max(...rb.map(p=>p.u)),minV=Math.min(...rb.map(p=>p.v)),maxV=Math.max(...rb.map(p=>p.v)),sample=Math.max(5*FT,Math.min(9*FT,pitch/7)),rows=[],reserve=Math.max(c.designOffset,Math.min(pitch*.45,90*FT));rows.reserve=reserve;let start=minV+pitch*.45+phase;for(let v=start,row=0;v<=maxV-pitch*.35;v+=pitch,row++){let runs=[],run=null;for(let u=minU;u<=maxU;u+=sample){let p=unrotate(u,v,angle),good=safeXY(p,c,reserve);if(good&&!run)run={u0:u,u1:u};else if(good)run.u1=u;else if(run){if(run.u1-run.u0>=65*FT)runs.push(run);run=null}}if(run&&run.u1-run.u0>=65*FT)runs.push(run);runs.sort((a,b)=>(b.u1-b.u0)-(a.u1-a.u0));runs=runs.slice(0,3).sort((a,b)=>a.u0-b.u0);if(runs.length)rows.push({v,row,runs:runs.map(r=>({a:unrotate(r.u0,v,angle),b:unrotate(r.u1,v,angle),len:r.u1-r.u0,u0:r.u0,u1:r.u1}))})}if(!rows.length){let v=(minV+maxV)/2,runs=[],run=null;for(let u=minU;u<=maxU;u+=sample){let p=unrotate(u,v,angle),good=safeXY(p,c,reserve);if(good&&!run)run={u0:u,u1:u};else if(good)run.u1=u;else if(run){if(run.u1-run.u0>=65*FT)runs.push(run);run=null}}if(run&&run.u1-run.u0>=65*FT)runs.push(run);if(runs.length)rows.push({v,row:0,runs:runs.map(r=>({a:unrotate(r.u0,v,angle),b:unrotate(r.u1,v,angle),len:r.u1-r.u0,u0:r.u0,u1:r.u1}))})}return rows}
function sequence(rows,reverse,firstLTR,start,finish){let rr=reverse?[...rows].reverse():[...rows],passes=[];rr.forEach((row,i)=>{let ltr=(i%2===0)===firstLTR,runs=[...row.runs].sort((a,b)=>ltr?a.u0-b.u0:b.u1-a.u1);runs.forEach(r=>passes.push({kind:'pass',a:ltr?r.a:r.b,b:ltr?r.b:r.a,len:r.len,row:row.row}))});if(!passes.length)return null;let passLen=passes.reduce((q,p)=>q+p.len,0),conn=d2(start,passes[0].a)+d2(passes[passes.length-1].b,finish);for(let i=1;i<passes.length;i++)conn+=d2(passes[i-1].b,passes[i].a);return{passes,passLen,conn,rawScore:passLen-.24*conn,rawLength:passLen+conn}}
function rng(seed){let x=seed|0||1;return()=>((x=Math.imul(1664525,x)+1013904223|0)>>>0)/4294967296}
function rawCandidates(c,start,finish){let r=rng(c.st.seed),list=[],base=(r()-.5)*Math.PI/12,pitches=[1,1.5,2.2,3.2,4.5,6].map(k=>c.st.separation*k);for(const pitch of pitches){let local=[];for(let k=0;k<6;k++){let angle=base+k*Math.PI/6;for(const phase of [0,pitch/2]){let rows=scanRows(c,angle,phase,pitch);for(const rev of [false,true])for(const dir of [false,true]){let s=sequence(rows,rev,dir,start,finish);if(s){s.angle=angle;s.pitch=pitch;s.phase=phase;s.reserve=rows.reserve||c.designOffset;local.push(s)}}}}local.sort((a,b)=>b.rawScore-a.rawScore);let keep=Math.max(c.bbox.maxX-c.bbox.minX,c.bbox.maxY-c.bbox.minY)>1000*FT?2:3;list.push(...local.slice(0,keep))}return list}
function pathLength(p){let z=0;for(let i=1;i<p.length;i++)z+=d2(p[i-1],p[i]);return z}
function materialize(seq,start,finish,g){let parts=[],cur=start,prevDir=null;for(const pass of seq.passes){let nextDir=unit(pass.a,pass.b).u,connector=astar(cur,pass.a,g);if(!connector)return null;if(pathLength(connector)>12*FT)parts.push({kind:'connector',path:connector,inDir:prevDir||unit(cur,pass.a).u,outDir:nextDir,reserve:seq.reserve});parts.push({kind:'pass',a:pass.a,b:pass.b,len:pass.len,row:pass.row});cur=pass.b;prevDir=nextDir}let connector=astar(cur,finish,g);if(!connector)return null;if(pathLength(connector)>8*FT)parts.push({kind:'connector',path:connector,inDir:prevDir||unit(cur,finish).u,outDir:unit(cur,finish).u,reserve:seq.reserve});return parts}
