'use strict';
function renderLists(){$('hazards').innerHTML=S.hazards.map((h,i)=>`<div class="item"><span>${h.type} · ${(h.r/FT).toFixed(0)} ft</span><button data-h="${i}">Remove</button></div>`).join('')+S.nogos.map((n,i)=>`<div class="item"><span>No-go area ${i+1}</span><button data-n="${i}">Remove</button></div>`).join('')||'<span class="note">No exclusions marked.</span>';$('hazards').querySelectorAll('[data-h]').forEach(b=>b.onclick=()=>{S.hazards.splice(+b.dataset.h,1);invalidateCourse();draw()});$('hazards').querySelectorAll('[data-n]').forEach(b=>b.onclick=()=>{S.nogos.splice(+b.dataset.n,1);invalidateCourse();draw()});$('elements').innerHTML=S.elements.map((e,i)=>`<div class="item"><span><b>${i+1}. ${e.name}</b><br><span class="tiny">${(S.route.length?polylineLLLength(e.path)/FT:0).toFixed(0)} ft · ${e.type}</span></span></div>`).join('')||'<span class="note">No generated elements yet.</span>';$('coords').innerHTML='<div class="cr"><b>#</b><b>Type</b><b>Side</b><b>Latitude</b><b>Longitude</b></div>'+S.cones.map(c=>`<div class="cr"><span>${c.id}</span><span>${c.type}${c.valid?'':' !'}</span><span>${c.side?c.side[0].toUpperCase():''}</span><span>${c.p[0].toFixed(6)}</span><span>${c.p[1].toFixed(6)}</span></div>`).join('')}
function polylineLLLength(p){let z=0;for(let i=1;i<p.length;i++)z+=distLL(p[i-1],p[i]);return z}
function renderStats(){let bad=S.cones.filter(c=>!c.valid).length,sl=S.cones.filter(c=>c.type==='slalom').length;$('len').textContent=S.length?Math.round(S.length/FT)+' ft':'—';$('speed').textContent=S.performance?S.performance.avg.toFixed(1)+' mph':'—';$('time').textContent=S.performance?S.performance.time.toFixed(1)+' s':'—';$('nc').textContent=S.cones.length;$('ne').textContent=S.elements.length;$('slaloms').textContent=sl;$('bad').textContent=bad;$('cross').textContent=S.warnings||0;if(!S.route.length)$('note').textContent='Create a route to calculate elements and cone locations.';else{let target=S.settings?.target||+$('target').value,err=Math.abs((S.performance?.avg||0)-target),status=err<=3?'Target speed band reached.':`Estimated average is ${err.toFixed(1)} mph from target.`;$('note').textContent=`${status} ${bad?'Resolve red cone conflicts.':'Cone geometry is inside the modeled footprint.'} ${S.warnings?'Review route-proximity warnings.':'No modeled crossings detected.'}`}}
function fmtArea(m2){let ft2=m2/(FT*FT);return ft2>=43560?(ft2/43560).toFixed(2)+' ac':Math.round(ft2).toLocaleString()+' ft²'}
function renderAnalysis(){let a=S.analysis;if(!a){$('siteArea').textContent=$('usableArea').textContent=$('availableLen').textContent=$('coverage').textContent='—';$('capacityBar').style.width='0';$('analysisNote').textContent=S.boundary.length?'Tap Analyze availability or generate a course.':'Draw a boundary to calculate site capacity.';return}$('siteArea').textContent=fmtArea(a.siteArea);$('usableArea').textContent=fmtArea(a.designArea);$('availableLen').textContent=Math.round(a.availableLength/FT)+' ft';let cov=S.length?Math.min(100,S.length/a.availableLength*100):0;$('coverage').textContent=S.length?cov.toFixed(0)+'%':'not planned';$('capacityBar').style.width=cov+'%';$('analysisNote').textContent=`Grid estimate after gate width, edge buffer, hazards, and no-go areas. ${a.candidateCount?`${a.candidateCount} geometry/speed variants tested.`:''}`}
$('analyze').onclick=()=>{let c=context();if(!c)return toast('Draw a boundary first');S.analysis=analyzeSite(c);draw();toast('Site availability calculated')};$('gen').onclick=generate;$('recones').onclick=()=>{if(!S.route.length)return toast('Draw a manual centerline first');manualElements();draw()};$('clear').onclick=()=>{S.route=[];S.cones=[];S.elements=[];S.performance=null;S.length=0;S.warnings=0;if(S.analysis)S.analysis.coverage=0;draw()};
function download(name,type,text){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),900)}
$('csv').onclick=()=>S.cones.length?download('autocross-cones.csv','text/csv','cone,element,type,side,latitude,longitude,valid\n'+S.cones.map(c=>[c.id,JSON.stringify(c.element||''),c.type,c.side||'',c.p[0],c.p[1],c.valid].join(',')).join('\n')):toast('No cones to export');
$('geo').onclick=()=>{let f=[];if(S.boundary.length)f.push({type:'Feature',properties:{kind:'boundary'},geometry:{type:'Polygon',coordinates:[[...S.boundary.map(p=>[p[1],p[0]]),[S.boundary[0][1],S.boundary[0][0]]]]}});S.nogos.forEach((n,i)=>f.push({type:'Feature',properties:{kind:'no-go',id:i+1},geometry:{type:'Polygon',coordinates:[[...n.map(p=>[p[1],p[0]]),[n[0][1],n[0][0]]]]}}));S.hazards.forEach((h,i)=>f.push({type:'Feature',properties:{kind:'hazard',id:i+1,type:h.type,radius_m:h.r},geometry:{type:'Point',coordinates:[h.p[1],h.p[0]]}}));S.elements.forEach((e,i)=>f.push({type:'Feature',properties:{kind:'course-element',id:i+1,type:e.type,name:e.name},geometry:{type:'LineString',coordinates:e.path.map(p=>[p[1],p[0]])}}));S.cones.forEach(c=>f.push({type:'Feature',properties:{kind:'cone',id:c.id,type:c.type,side:c.side,element:c.element,valid:c.valid},geometry:{type:'Point',coordinates:[c.p[1],c.p[0]]}}));download('autocross-course.geojson','application/geo+json',JSON.stringify({type:'FeatureCollection',properties:{performance:S.performance,analysis:S.analysis,settings:S.settings},features:f},null,2))};
$('save').onclick=()=>{localStorage.apexCourseMax=JSON.stringify(S);toast('Saved on this device')};$('load').onclick=()=>{try{let x=JSON.parse(localStorage.apexCourseMax);S={...blank(),...x};draw();if(S.boundary.length)map.fitBounds(S.boundary);toast('Saved project loaded')}catch(e){toast('No saved project found')}};
draw();if(innerWidth<=700)$('drawer').classList.add('closed');
